#!/bin/bash
yum update -y
yum install httpd -y
cd /var/www/html
echo "Today is May 29 2021, The Awesome JJTech Bliss Batch students are now studying Route53, and will explore all the routing policies including failover based routing, weighted based routing, latency based routing, geolocation and simple based routing policies" > index.html
service httpd start
chkconfig httpd on




#!/bin/bash
yum update -y
yum install httpd -y
cd /var/www/html
echo "JJ Tech Inc Disaster Recovery strategy include using Route53 Failover Based Routing" > index.html
service httpd start
chkconfig httpd on
